spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  application:
    name: partner-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner
    username: root
    password: 123456
  # session 失效时间 30 天
  session:
    timeout: 2592000
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
#    active: dev
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 8102
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tDqVTD4RNi5n6NiGjFH
      keysecret: aGzwOa5gQ942Z5ZXcU1BjmdoPxyU0N
      bucketname: shierpartner