server:
  port: 8102
  servlet:
    context-path: /api
    session:
      cookie:
        domain: partner.kongshier.top
        same-site: lax
        secure: false
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.134.37.7:3306/partner?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: shier
  # session 失效时间 30 天
  session:
    timeout: 2592000
    store-type: redis
  # redis配置
  redis:
    port: 6379
    host: 8.134.37.7
    database: 0
    password: kcsen281017
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tDqVTD4RNi5n6NiGjFH
      keysecret: aGzwOa5gQ942Z5ZXcU1BjmdoPxyU0N
      bucketname: shierpartner